### ISSUE TITLE
Navigation links

### ISSUE THREAD

**Issue by gregz981** [echicken/synchronet-web-v4#34]
When I click on Forums and Files, I do not show any directories in Files, for the Forums, I do not show any messages in the Dove-Net forums and Local/Local Notices.  It was working before moving to webv4.

**Comment by echicken** [comment]
This is obvious but included for completeness: Message Groups, Message Areas, File Libraries, and File Directories will only show up if the current user has access to them. When you aren't logged in to the web interface, you are browsing as the user with alias 'Guest' or whichever user is specified in modopts.ini -> [web] -> guest, so that user's permissions matter.

It could be your build of Synchronet. I'm not sure at this point if I'm using features that were introduced after 3.16c or even earlier 3.17a builds. An update there, if you want to, might help (but I have no idea if it will).

File Directories in particular will not show up if they are empty, and this is normal.

I don't have any other ideas at the moment and haven't heard of this problem before. Please watch your logs while loading these parts of the website, and if you see any errors, please share them.

**Comment by gregz981** [comment]
This is what shows when I debug through console going to any of the dove-net forums that have messages showing when I go in through telnet and verify the system has downloaded.
?page=001-forum.ssjs&group=1:212 Uncaught ReferenceError: registerEventListener is not defined
    at ?page=001-forum.ssjs&group=1:212
(anonymous) @ ?page=001-forum.ssjs&group=1:212

**Comment by echicken** [comment]
It appears that registerEventListener isn't currently defined in any of the server-side scripts, so it's likely that your copy of 001-forum.ssjs is out of date.

Try copying pages/.examples/001-forum.ssjs up to pages/001-forum.ssjs and see if that helps.

**Comment by gregz981** [comment]
Added latest Synchro dev files and now I can see messages, cannot post to local boards or emails.  Also getting error that logonlist_lib.js not in sidebar.

**Comment by gregz981** [comment]
Resolved.  I had to also go into the Synchronet CVS and pull the proper files over to fix.  All works now with Synchro 3.17b.  We can call this closed.
